### PR TITLE
feat(music): Musical Commands

### PR DESCRIPTION
**Pull request by PenPow**
**Please describe the changes this PR makes and why it should be merged:**
This Mega Thread compiles the documentation and features for the music features.

Regarding the discussion in #14, I am going to go with the @discordjs/voice library because that is officially supported by the discord.js support, and it also supports V13, which is the version we are actively using

**This Pull Request is still a Draft, do not use it in Production**

### CODE REVIEW

**Comment by PenPow** [comment]
- [X] Play
- [ ] Pause
- [ ] Resume
- [ ] Skip
- [ ] Leave
- [ ] Queue
- [ ] Volume - _Awaiting Research into Voice Lib_
- [ ] Lyrics

**Comment by PenPow** [comment]
Currently experiencing some technical issues with it disconnecting, especially since documentation is still limited.

**Comment by PenPow** [comment]
> Currently experiencing some technical issues with it disconnecting, especially since documentation is still limited.

I have a hacky workaround while I work this out

**Comment by KyomiDev** [comment]
> > Currently experiencing some technical issues with it disconnecting, especially since documentation is still limited.
> 
> I have a hacky workaround while I work this out

Fixed in 0aaf815, the issue was that when it disconnects it doesn't modify the collection to remove it, so it tries to resume a voice connection that has been destroyed, which will never truly connect.

**Review by KyomiDev — APPROVED** [review]

**Pull request merged**
