### PR TITLE
refactor(slashies): Migrate Slash Commands to be deployed via command

### PR DESCRIPTION
**Pull request by PenPow**
Resolves discussion in #5

### CODE REVIEW

**Comment by PenPow** [comment]
Leaving as draft until slash commands have the builders added, will close the related issue.

**Review by KyomiDev — APPROVED** [review]
LGTM

**Comment by KyomiDev** [comment]
This requires a rebase

**Comment by KyomiDev** [comment]
This requires a rebase.

**Comment by KyomiDev** [comment]
Command Implemented in another PR

**Pull request closed without merging**
